import sqlalchemy as sa

from alembic.op import create_table, drop_table

# revision identifiers, used by Alembic.
revision = '3d98ad3a4faf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    create_table(
        'menu',
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title'),
    )
    create_table(
        'submenu',
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('parent_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['menu.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title'),
    )
    create_table(
        'dish',
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('price', sa.String(), nullable=False),
        sa.Column('parent_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['submenu.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    drop_table('dish')
    drop_table('submenu')
    drop_table('menu')
    # ### end Alembic commands ###
