name: menu_workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install pre-commit
      run: |
        pip install pre-commit
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - uses: pre-commit/action@v3.0.0
